/**
 * Base de connaissances RAG HawaeMD — 22 chunks cliniques officiels (port v50).
 * Référentiels FIGO / CNGOF / ESHRE / HAS / RCOG / ISSHP, etc.
 */

export type RagDomain = "OBST" | "GYN" | "PMA";

export type RagChunk = {
  id: string;
  source: string;
  domain: RagDomain;
  topic: string;
  title: string;
  year: number;
  evidence: string;
  keywords: string[];
  text: string;
};

export const SEED_KB: RagChunk[] = [
  {
    id: "figo2021-fgr-classification",
    source: "FIGO 2021",
    domain: "OBST",
    topic: "FGR",
    title: "FGR Précoce — Classification FIGO 2021 Stades I–IV",
    year: 2021,
    evidence: "A",
    keywords: ["FGR", "RCIU", "restriction", "croissance", "stade", "classification", "Doppler", "AO", "DV", "ombilicale", "ACM", "CPR", "BPP", "ductus"],
    text: "FGR PRÉCOCE (< 32 SA) — CLASSIFICATION FIGO 2021 :\nSTADE I : PFE < p3 OU (biométrie p3-10 + ≥ 1 critère) : IP AO > p95, IP ACM < p5, CPR < p5, IP UtA moyen > p95. Surveillance bi-hebdomadaire ambulatoire (Doppler + CTG). Corticothérapie envisagée si < 34 SA.\nSTADE II : Artère ombilicale AEDF (absent end-diastolic flow). Hospitalisation. Corticothérapie systématique si < 34 SA. Extraction à 34 SA si stable.\nSTADE III : AO REDF (flux inversé) OU IP DV > p95. Extraction à 30-32 SA. MgSO4 neuroprotecteur systématique si < 32 SA.\nSTADE IV : CTG pathologique (décélérations tardives, tracé plat) OU BPP ≤ 4/10 OU DV onde A inversée. Extraction IMMÉDIATE si viable (> 24 SA).\n\nFGR TARDIF (≥ 32 SA) :\nMajeur : PFE < p3. Mineur : PFE p3-10 + 2 critères parmi IP ACM < p5, CPR < p5, IP UtA > p95. Extraction : 37-38 SA si PFE < p3 ; 37-40 SA si PFE p3-10 avec critères anormaux.\n\nBPP (Manning) — 5 paramètres × 2 pts (30 min observation) :\nNST + mouvements respiratoires + mouvements actifs + tonus + LA.\n≤ 4/10 = extraction urgente. 6/10 = répéter 24h. ≥ 8/10 = rassurant.\n\nVoie accouchement : Stade I-II → tentative VB avec monitoring continu. Stade III-IV → césarienne recommandée. Prévention récidive : Aspirine 150 mg/j dès T1 si ATCD FGR précoce.",
  },
  {
    id: "figo2021-fgr-definition",
    source: "FIGO 2021",
    domain: "OBST",
    topic: "FGR",
    title: "FGR — Définition, étiologies, marqueurs Doppler",
    year: 2021,
    evidence: "A",
    keywords: ["FGR", "PFE", "percentile", "biométrie", "Hadlock", "placenta", "Doppler", "ACM", "DV", "ductus", "IP", "SGA", "constitutionnel"],
    text: "DÉFINITION FGR : fœtus n'atteignant pas son potentiel génétique de croissance, distinct du SGA constitutionnel (petit mais sain, Doppler normaux).\n\nBIOMÉTRIE : PFE (Hadlock : BIP + PC + CA + LF). Références Salomon 2011.\n\nMARQUEURS DOPPLER :\n- IP Artère Ombilicale (AO) : résistances placentaires. AEDF puis REDF = stades avancés.\n- IP ACM : vasodilatation cérébrale (brain sparing). IP ACM < p5 = redistribution.\n- CPR = IP ACM / IP AO. < 1.0 ou < p5 = redistribution hémodynamique.\n- IP Ductus Venosus (DV) : défaillance cardiaque droite. Onde A nulle/inversée = terminal.\n- IP Artères Utérines (UtA) : défaut remodelage trophoblastique si élevé au T2-T3.\n\nÉTIOLOGIES :\nInsuffisance placentaire 80%, anomalies chromosomiques/structurelles 10%, infections (CMV, toxoplasmose, rubéole) 5%, causes maternelles : PE, HTA chronique, thrombophilies, LED, SAPL, insuffisance rénale, malnutrition sévère.",
  },
  {
    id: "aspre-screening-prevention",
    source: "FIGO PE 2019 + ASPRE NEJM 2017",
    domain: "OBST",
    topic: "PE",
    title: "Prééclampsie — Screening T1 et prévention aspirine (ASPRE)",
    year: 2019,
    evidence: "A",
    keywords: ["prééclampsie", "PE", "screening", "ASPRE", "aspirine", "prévention", "PlGF", "PAPP-A", "MAP", "UtA", "risque", "T1", "premier trimestre"],
    text: "SCREENING PE 1ER TRIMESTRE (11-13+6 SA) — ALGORITHME FMF :\nCombine : (1) facteurs maternels, (2) MAP (pression artérielle moyenne), (3) IP UtA moyen (Doppler), (4) PlGF MoM, (5) PAPP-A MoM.\n\nSEUIL PE PRÉTERME (< 37 SA) : risque ≥ 1/100 → Aspirine 150 mg/j.\n\nRÉSULTATS ASPRE (Rolnik, NEJM 2017, n=1776) :\nAspirine 150 mg/j en prise nocturne 11-14 SA → arrêt 36 SA.\nRéduction PE préterme : 62% (NNT = 8). PE sévère < 34 SA : 82%.\n\nINDICATIONS ASPIRINE HORS ALGORITHME FMF :\n≥ 1 facteur majeur : ATCD PE, HTA chronique, diabète T1/T2, maladie rénale, LED, SAPL, grossesse multiple.\n≥ 2 facteurs modérés : nulliparité, IMC ≥ 30, âge ≥ 35, intervalle > 10 ans, ATCD famille PE.\n\nSURVEILLANCE T2-T3 si risque élevé :\nPlGF à 20-24 SA (< 100 pg/mL = risque PE × 8), UtA à 20-24 SA, biométrie fœtale, TA régulière.",
  },
  {
    id: "pe-diagnostic-classification",
    source: "ISSHP 2018 + CNGOF 2020",
    domain: "OBST",
    topic: "PE",
    title: "Prééclampsie — Définition ISSHP, critères sévérité, HELLP",
    year: 2020,
    evidence: "A",
    keywords: ["prééclampsie", "diagnostic", "HTA", "protéinurie", "sévère", "critères", "HELLP", "éclampsie", "Chaussier", "définition", "ISSHP", "PE"],
    text: "DÉFINITION PE (ISSHP 2018) :\nHTA gestationnelle (PAS ≥ 140 ou PAD ≥ 90 mmHg après 20 SA, confirmée 2 mesures 4h) + ≥ 1 atteinte systémique.\n\nCRITÈRES DE SÉVÉRITÉ (CNGOF 2020) :\n- Neurologique : céphalées persistantes, troubles visuels, hyperréflexie, convulsions\n- TA : PAS ≥ 160 ou PAD ≥ 110 mmHg\n- Rénale : protéinurie > 5 g/24h, créatinine > 90 µmol/L, oligurie < 500 mL/24h\n- Hépatique : transaminases > 2×N, signe de Chaussier (douleur épigastrique en barre)\n- Hématologique : thrombocytopénie < 100 G/L, hémolyse, CIVD\n- Pulmonaire : œdème pulmonaire, SpO2 < 95%\n\nHELLP SYNDROME :\nH = Hémolyse (LDH > 600 UI/L, bili > 20 µmol/L, schizocytes)\nEL = ASAT/ALAT > 70 UI/L\nLP = Plaquettes < 100 G/L\n\nTRAITEMENT PE SÉVÈRE :\nAntihypertenseurs IV : Nicardipine 5-15 mg/h IVSE (1ère ligne).\nObjectif TA : PAS 140-155, PAD 90-105 mmHg.\nMgSO4 OBLIGATOIRE : bolus 4 g IV / 20 min, puis 1-2 g/h IVSE.\nCorticothérapie systématique si < 34 SA.\nTerme extraction : ≥ 37 SA PE légère ; individuelle PE sévère.",
  },
  {
    id: "pe-urgence-protocole",
    source: "CNGOF 2020 + HAS 2021",
    domain: "OBST",
    topic: "PE",
    title: "PE sévère — Protocole urgence, MgSO4, antihypertenseurs IV",
    year: 2021,
    evidence: "A",
    keywords: ["prééclampsie", "sévère", "urgence", "MgSO4", "nicardipine", "labétalol", "protocole", "extraction", "IVSE", "ROT", "antidote", "calcium"],
    text: "PROTOCOLE URGENCE PE SÉVÈRE :\n\n1. ÉVALUATION : TA / 15 min, SpO2, scope, diurèse horaire, bilan hépatique + rénal + NFS + coag en STAT, CTG continu.\n\n2. CONTRÔLE TA si PAS ≥ 160 ou PAD ≥ 110 :\nNicardipine (Loxen) : 5 mg/h IVSE → titrer +2.5 mg/15 min → max 15 mg/h.\nLabétalol (Trandate) : 20 mg IVL 2 min, répétable 80 mg/10 min, max 300 mg.\nObjectif PAS 140-155, PAD 90-105 mmHg.\n\n3. SULFATE DE MAGNÉSIUM (MgSO4 2 g/mL) :\nBolus : 4 g dilués 100 mL SSI en 20 min. Entretien : 1-2 g/h IVSE.\nSurveillance horaire : ROT (abolition = surdosage), diurèse, FR (arrêt si < 12/min).\nAntidote : Gluconate de calcium 1 g IV.\n\n4. CORTICOTHÉRAPIE si < 34+6 SA :\nBétaméthasone 12 mg IM × 2 doses espacées 24h.\n\n5. DÉCISION EXTRACTION :\n≥ 34 SA + PE sévère / HELLP → extraction après stabilisation 24-48h. > 37 SA → extraction. < 34 SA → expectative si stabilité stricte.",
  },
  {
    id: "fmf-t21-algorithm",
    source: "FMF Nicolaides 2011 + Spencer 2004",
    domain: "OBST",
    topic: "T21",
    title: "Dépistage T21 — Algorithme combiné 1er trimestre FMF",
    year: 2011,
    evidence: "A",
    keywords: ["T21", "trisomie 21", "dépistage", "NT", "clarté nucale", "PAPP-A", "hCG", "risque", "FMF", "Nicolaides", "os nasal", "ductus", "tricuspide", "cfDNA", "DPNI"],
    text: "ALGORITHME FMF DE DÉPISTAGE T21 (11-13+6 SA) :\n\nMARQUEURS 1ER NIVEAU :\n- Risque de fond âge maternel (table Nicolaides 2011)\n- NT (clarté nucale) : sigma 0.26 MoM (Spencer 2004). NT ≥ 3.5 mm = marqueur fort.\n- PAPP-A MoM : < 0.40 = risque T21 + PE + FGR précoce.\n- βhCG libre MoM : > 2.0 (T21) ; < 0.5 (T18/T13).\n\nMARQUEURS 2ÈME NIVEAU :\n- Os nasal absent : LR+ = 23 (Cicero 2006)\n- Ductus venosus onde A inversée : LR+ = 7.8 (Maiz 2009)\n- Régurgitation tricuspidienne : LR+ = 4.6\n- Angle fronto-nasal < 47° : LR+ = 5.3\n\nPERFORMANCES :\nCombiné seul (âge + NT + PAPP-A + βhCG) : 85-90% détection / TFP 5%.\nAvec marqueurs 2ème niveau : 95-96% / TFP 3%.\ncfDNA (DPNI) : > 99% / TFP < 0.1%.\n\nSEUILS ET CONDUITE :\nRisque ≥ 1/50 → diagnostic invasif d'emblée (biopsie trophoblaste ou amniocentèse).\nRisque 1/50-1/1000 → proposer cfDNA.\nRisque < 1/1000 → rassurant.",
  },
  {
    id: "rcog-vte-prophylaxie",
    source: "RCOG GTG 37a 2015",
    domain: "OBST",
    topic: "VTE",
    title: "Thromboprophylaxie grossesse — Score VTE RCOG GTG 37a",
    year: 2015,
    evidence: "A",
    keywords: ["VTE", "TVP", "thrombose", "HBPM", "prophylaxie", "RCOG", "risque", "embolie", "score", "énoxaparine", "anti-Xa", "SAPL", "thrombophilie"],
    text: "SCORE VTE RCOG GTG 37a 2015 :\n\nINDICATION HBPM FORMELLE (sans calcul) :\n- VTE antérieure non provoquée ou liée estrogènes\n- Thrombophilie haut risque : SAPL, déficit AT III, FVL homozygote, thrombophilie combinée\n- Hospitalisation > 3 jours ou chirurgie > 30 min en cours de grossesse\n\nFACTEURS COTÉS — ANTÉPARTUM :\n- VTE antérieure liée chirurgie: 3 pts | Thrombophilie bas risque: 1 pt\n- IMC > 30: 1 pt | IMC > 40: 2 pts | Âge > 35: 1 pt | Para ≥ 3: 1 pt\n- Grossesse multiple: 1 pt | FIV: 1 pt | PE: 1 pt | Immobilisation ≥ 7j: 1 pt\n\nSEUILS :\nScore ≥ 4 anté-partum → HBPM dès 1er trimestre.\nScore 3 anté-partum → HBPM à partir de 28 SA.\nScore ≥ 2 post-partum → HBPM 10 jours.\n\nPOSOLOGIE :\nÉnoxaparine (Lovenox) : 0.4 mL (4 000 UI) SC/j. < 50 kg : 0.2 mL. > 90 kg : 0.6 mL.\nArrêt 24h avant déclenchement ou APD.",
  },
  {
    id: "col-court-prematurite",
    source: "FIGO 2022 + CNGOF 2016",
    domain: "OBST",
    topic: "Prématurité",
    title: "Col court — Screening, progestérone, cerclage, MAP",
    year: 2022,
    evidence: "A",
    keywords: ["col", "court", "cervical", "longueur", "CL", "prématurité", "MAP", "cerclage", "progestérone", "tocolyse", "atosiban", "corticothérapie", "bétaméthasone"],
    text: "LONGUEUR CERVICALE (LC) — VALEURS :\nMesure par écho endovaginale. Normal ≥ 25 mm entre 18-24 SA.\nLC 16-24 mm : risque AP × 3. LC 10-15 mm : risque × 6. LC < 10 mm : risque très élevé.\n\nPRISE EN CHARGE :\n1. Singleton + ATCD AP ou perte 2ème trim + LC < 25 mm : Progestérone vaginale 200 mg/j (Utrogestan) → 36 SA. Cerclage si béance.\n2. Singleton sans ATCD + LC 10-24 mm découverte 18-24 SA : Progestérone vaginale 200 mg/j. NNT ≈ 8 pour éviter 1 AP < 34 SA.\n3. Gémellaire + LC < 25 mm : Progestérone NON recommandée. Cerclage non recommandé en routine.\n4. LC < 10 mm / béance + ATCD sévère : Cerclage d'urgence (MacDonald ou Shirodkar).\n\nMAP — TOCOLYSE (24-34 SA, membranes intactes) :\n1ère ligne : Atosiban (Tractocile) bolus 6.75 mg puis 18 mg/h × 3h puis 6 mg/h max 45h.\nCorticothérapie : Bétaméthasone 12 mg IM × 2 doses 24h si 24-34+6 SA.\nMgSO4 neuroprotecteur si < 32 SA : 4 g bolus puis 1 g/h × 24h.\nTransfert in utero si < 32 SA et plateau technique requis.",
  },
  {
    id: "eshre-ohss-complet",
    source: "ESHRE 2020",
    domain: "PMA",
    topic: "OHSS",
    title: "OHSS — Classification, facteurs risque, prévention, traitement",
    year: 2020,
    evidence: "A",
    keywords: ["OHSS", "hyperstimulation", "ovarienne", "CFA", "AMH", "agoniste", "antagoniste", "freeze", "cabergoline", "albumine", "coasting", "trigger"],
    text: "CLASSIFICATION OHSS (ESHRE 2020) :\nLÉGER : inconfort abdominal, ovaires < 8 cm. Ambulatoire.\nMODÉRÉ : ascite échographique, ovaires 8-12 cm. HDJ.\nSÉVÈRE : ascite clinique, ovaires > 12 cm, hématocrite > 45%, leucocytes > 15G/L, oligurie, créatinine > 133 µmol/L, hypoalbuminémie < 30 g/L. HOSPITALISATION.\nCRITIQUE : torsion, rupture, épanchements pleuraux/péricardiques, CIVD. RÉANIMATION.\n\nFACTEURS DE RISQUE :\nCFA > 15 follicules, AMH > 3.5 ng/mL, SOPK, âge < 30, IMC < 20, ATCD OHSS, > 20 follicules, E2 > 3500 pg/mL, > 20 ovocytes.\n\nPRÉVENTION :\n1. Protocole ANTAGONISTE GnRH (moins de risque).\n2. Trigger GnRH AGONISTE (Décapeptyl 0.2 mg SC) → FREEZE-ALL obligatoire.\n3. Coasting : arrêt FSH 1-3 j avant trigger si E2 > 5000 pg/mL.\n4. Cabergoline 0.5 mg/j × 8 j après trigger (anti-VEGF).\n5. Albumine 20% 50 g IV au jour de ponction si risque très élevé.\n\nTRAITEMENT SÉVÈRE :\nHospitalisation, remplissage prudent (albumine 5%), HBPM prophylaxie (thrombose × 7), drainage ascite si gêne respiratoire. Interdire transfert embryonnaire.",
  },
  {
    id: "poseidon-classification",
    source: "Poseidon Group 2016 Hum Reprod",
    domain: "PMA",
    topic: "POSEIDON",
    title: "POSEIDON — Classification POR et stratégies FIV",
    year: 2016,
    evidence: "B",
    keywords: ["POSEIDON", "POR", "mauvaise", "réponse", "ovocyte", "FIV", "AMH", "CFA", "DuoStim", "FSH", "protocole", "accumulation", "DHEA", "don"],
    text: "CLASSIFICATION POSEIDON 2016 :\nDéfinition POR : < 4 complexes cumulo-ovocytaires par ponction.\n\nGROUPE 1 : < 35 ans + bonne réserve (AMH ≥ 1.2 ng/mL ET CFA ≥ 5) + < 4 ovocytes INATTENDU.\nStratégie : dose FSH maximale (300-450 UI/j), changer protocole, trigger dual, DuoStim, DHEA.\n\nGROUPE 2 : ≥ 35 ans + bonne réserve + < 4 ovocytes inattendu.\nStratégie G1 + discussion don ovocytes si échecs multiples.\n\nGROUPE 3 : < 35 ans + MAUVAISE réserve (AMH < 1.2 ng/mL OU CFA < 5).\nStratégie : dose FSH maximale d'emblée, FSH+LH, mini-IVF, accumulation multi-ponctions.\n\nGROUPE 4 : ≥ 35 ans + mauvaise réserve.\nStratégie : accumulation obligatoire, DuoStim systématique, don ovocytes à discuter franchement (LBR propre < 20% si > 40 ans).\n\nDuoStim : Ponction 1 phase folliculaire → Ponction 2 phase lutéale (même cycle).\nLBR cumulé ≈ 45-60% vs 30-40% stimulation unique.\n\nOBJECTIFS : G1-2 ≥ 5 ovocytes MII/ponction. G3-4 : accumuler ≥ 5 ovocytes MII totaux.",
  },
  {
    id: "iota-adnex-malignite",
    source: "IOTA 2016 + ESGO 2020",
    domain: "GYN",
    topic: "Kyste ovarien",
    title: "ADNEX/IOTA — Caractérisation masse annexielle, risque malignité",
    year: 2016,
    evidence: "A",
    keywords: ["ADNEX", "kyste", "ovarien", "malignité", "IOTA", "CA-125", "HE4", "ROMA", "masse", "annexielle", "bénin", "malin", "chirurgie", "oncologie"],
    text: "MODÈLE ADNEX (IOTA, Van Calster 2016) — 6 PARAMÈTRES :\nÂge | CA-125 (UI/mL) | Type centre | Taille lésion (mm) | % composante solide | Nombre papilles + cloisons, ombres, ascite.\n\nPROBABILITÉ MALIGNITÉ :\n< 1% = bénin | 1-10% = probablement bénin | 10-30% = zone grise | 30-50% = probablement malin | > 50% = malin.\nSeuil orientation oncologie : > 10-15% selon centre.\n\nRÈGLES SIMPLES IOTA (Timmerman 2010) :\nBénins (B) : uniloculaire, composante solide < 7 mm, ombre acoustique, multiloculaire < 10 cm, pas de flux.\nMalins (M) : partie solide irrégulière > 7 mm, ascite, ≥ 4 papilles, multiloculaire-solide > 10 cm, flux abondant (score 4).\nRègle : 1+ B et 0 M → bénin. 1+ M et 0 B → malin. B+M → appliquer ADNEX.\n\nORIENTATION :\nBénin probable → suivi 6-12 mois ou kystectomie coelioscopique.\nRisque intermédiaire → RCP, chirurgie avec exploration péritonéale.\nMalin probable → centre expert gynéco-oncologie, laparotomie stadification.",
  },
  {
    id: "roma-score",
    source: "Moore 2010 Gynecol Oncol (FDA)",
    domain: "GYN",
    topic: "Cancer ovaire",
    title: "ROMA — Risk of Ovarian Malignancy Algorithm",
    year: 2010,
    evidence: "A",
    keywords: ["ROMA", "HE4", "CA-125", "malignité", "cancer", "ovaire", "pré-ménopause", "post-ménopause", "seuil", "algorithme", "formule"],
    text: "ROMA — VALIDÉ FDA 2011 :\n\nFORMULES :\nPré-ménopause : PI = -12.0 + 2.38 × LN(HE4) + 0.0626 × LN(CA-125)\nPost-ménopause : PI = -8.09 + 1.04 × LN(HE4) + 0.732 × LN(CA-125)\nProbabilité (%) = exp(PI) / [1 + exp(PI)] × 100\n\nSEUILS (Moore 2010) :\nPré-ménopause ≥ 11.4% → haut risque (Se 75.6%, Sp 74.8%, VPN 94.5%)\nPost-ménopause ≥ 25.3% → haut risque (Se 92.3%, Sp 76.0%, VPN 97.1%)\n\nAVANTAGES HE4 :\nHE4 NON élevé dans endométriose, grossesse, maladies bénignes. Meilleure spécificité que CA-125.\n\nLIMITES :\nInsuffisance rénale → HE4 artificiellement élevé. Tumeurs germinales ou stromales → ROMA non pertinent.\n\nCOMBINAISON :\nROMA > seuil + ADNEX > 15% → référer en gynécologie-oncologie. Chirurgie : cytologie ascite, biopsies péritonéales, omentectomie.",
  },
  {
    id: "eshre-endometriose-2022",
    source: "ESHRE 2022",
    domain: "GYN",
    topic: "Endométriose",
    title: "Endométriose — Diagnostic, classification rASRM/Enzian, traitement",
    year: 2022,
    evidence: "A",
    keywords: ["endométriose", "diagnostic", "laparoscopie", "rASRM", "Enzian", "diénogest", "chirurgie", "douleur", "infertilité", "FIV", "AMH", "ESHRE"],
    text: "ENDOMÉTRIOSE (ESHRE 2022) :\nDélai diagnostique moyen : 7-10 ans.\n\nCLINIQUE : dysménorrhée (EVA > 6), dyspareunie profonde, dyschezie cyclique, douleurs pelviennes chroniques (> 6 mois), signes urinaires/rectaux cycliques, infertilité.\n\nCLASSIFICATION :\nrASRM I-IV (chirurgical). Enzian : endométriose profonde (nodules rectovaginaux, ligaments sacrés, vésicaux, urétéraux).\n\nIMAGERIE :\nÉcho TV : kystes (image verre dépoli), nodules profonds. IRM pelvis : bilan exhaustif.\n\nTRAITEMENT MÉDICAL :\n1ère ligne : AINS + estroprogestatifs continus.\n2ème ligne : Diénogest (Visanne) 2 mg/j (référence) | MPA 150 mg/3 mois.\n3ème ligne : Agonistes GnRH 3-6 mois + add-back therapy.\n\nCHIRURGIE : kystectomie (pas vaporisation). Exérèse nodule profond si symptomatique. Surveiller AMH avant/après chirurgie ovarienne.\n\nINFERTILITÉ + ENDOMÉTRIOSE :\nStades I-II : chirurgie améliore fertilité spontanée. Stades III-IV : FIV en 1ère intention si > 38 ans ou AMH < 1.2 ng/mL.",
  },
  {
    id: "cngof-avac-tolac-2020",
    source: "CNGOF 2020",
    domain: "OBST",
    topic: "AVAC",
    title: "AVAC/TOLAC — Critères éligibilité, score Flamm, LUS, rupture utérine",
    year: 2020,
    evidence: "A",
    keywords: ["AVAC", "TOLAC", "utérus", "cicatriciel", "césarienne", "rupture", "Flamm", "Geiger", "LUS", "SUI", "Bandl", "éligibilité", "score"],
    text: "AVAC (Accouchement Voie Basse Après Césarienne) :\n\nÉLIGIBILITÉ CNGOF 2020 :\nFavorable : cicatrice unique segmentaire transverse, pas d'indication formelle CS, plateau technique 24h/24. Contre-indication absolue : cicatrice corporéale/fondique, utérus triplement cicatriciel, rupture antérieure.\nTaux succès AVAC : 65-75% si tentative autorisée.\n\nSCORE DE FLAMM & GEIGER :\n- Âge < 40 ans : 2 pts\n- ATCD accouchement voie basse : 4 pts\n- Motif CS non récurrent (siège, SFA) : 1 pt\n- Effacement col admission : complet 2, incomplet 1, non effacé 0\n- Dilatation col admission : ≥ 4 cm = 2, < 4 cm = 0\nScore ≥ 8 : succès > 85%. Score < 4 : < 50%.\n\nLUS ÉCHOGRAPHIQUE (36-38 SA) :\n≥ 3.5 mm : risque déhiscence < 1% → AVAC autorisé.\n2.5-3.5 mm : zone grise, discussion individualisée.\n< 2.5 mm : risque élevé ≈ 3-4%, CS programmée à discuter.\n\nSIGNES DE RUPTURE :\nAnneau de Bandl, douleur sus-pubienne entre contractions, bradycardie fœtale soudaine, ascension présentation, métrorragies. Traitement : laparotomie immédiate.",
  },
  {
    id: "iadpsg-gdm-2013",
    source: "IADPSG 2010 + OMS 2013 + CNGOF",
    domain: "OBST",
    topic: "GDM",
    title: "Diabète gestationnel — Dépistage IADPSG, prise en charge, accouchement",
    year: 2013,
    evidence: "A",
    keywords: ["GDM", "diabète", "gestationnel", "HGPO", "glycémie", "IADPSG", "insuline", "dépistage", "objectifs", "accouchement", "macrosomie"],
    text: "DIABÈTE GESTATIONNEL — IADPSG 2010 / OMS 2013 :\n\nDÉPISTAGE : glycémie jeûn 8-12 SA (précoce). HGPO 75 g à 24-28 SA.\n\nCRITÈRES DIAGNOSTIQUES HGPO 75 g (≥ 1 valeur anormale suffit) :\nÀ JEUN ≥ 5.1 mmol/L (0.92 g/L)\nÀ 1H ≥ 10.0 mmol/L (1.80 g/L)\nÀ 2H ≥ 8.5 mmol/L (1.53 g/L)\nDiabète manifeste si jeûn ≥ 7.0 mmol/L ou 2h ≥ 11.1 mmol/L.\n\nFACTEURS DE RISQUE :\nIMC ≥ 25, âge ≥ 35, ATCD DG, macrosomie antérieure, SOPK, ethnie à risque.\n\nOBJECTIFS GLYCÉMIQUES :\nJeûn < 5.0 mmol/L | Post-prandial 1h < 7.8 | Post-prandial 2h < 6.7 mmol/L.\n\nTRAITEMENT :\n1ère ligne : régime (40-50% glucides, IG bas, 3 repas + 2-3 collations).\nInsuline si objectifs non atteints en 10-14 jours.\n\nSURVEILLANCE FŒTALE :\nBiométrie à 32 SA. Accouchement : 39-40 SA si insulino-traité | 40-41 SA si régime seul.\nPost-partum : HGPO 75 g à 3 mois (25-30% → DT2 dans 5 ans).",
  },
  {
    id: "popq-prolapsus-2021",
    source: "ICS 2002 + CNGOF 2021",
    domain: "GYN",
    topic: "Prolapsus",
    title: "Prolapsus génital — POP-Q, PFDI-20, traitement CNGOF 2021",
    year: 2021,
    evidence: "A",
    keywords: ["prolapsus", "POP-Q", "cystocèle", "rectocèle", "hystéroptose", "stade", "pessaire", "chirurgie", "promontofixation", "rééducation", "PFDI"],
    text: "CLASSIFICATION POP-Q (ICS 2002) — POINTS / HYMEN (= 0 mm) :\nParoi ant : Aa et Ba. Apex : C et D. Paroi post : Ap et Bp.\n\nSTADES :\nStade 0 : aucun. Stade I : > -1 cm hymen. Stade II : -1 à +1 cm.\nStade III : > +1 cm mais < TVL-2. Stade IV : éversion complète.\n\nPFDI-20 (Barber 2005) — 3 SOUS-SCORES :\nPOPDI-6 + CRADI-8 + UDI-6 = Score 0-300.\nChangement cliniquement significatif : ≥ 45 points.\n\nPRISE EN CHARGE CNGOF 2021 :\nStade I-II asymptomatique → surveillance, rééducation préventive.\nStade II symptomatique → rééducation (20 séances) + pessaire.\nStade III-IV ou échec conservateur → CHIRURGIE.\n\nVOIES CHIRURGICALES :\nVaginale : colporraphie ant + post, hystérectomie vaginale.\nCoelioscopique : promontofixation (sacrocolpopexie) ± culdoplastie Halban. Gold standard apical.",
  },
  {
    id: "minipiers-score",
    source: "von Dadelszen 2011 Lancet",
    domain: "OBST",
    topic: "PE",
    title: "miniPIERS — Score pronostique PE, issue défavorable 48h",
    year: 2011,
    evidence: "B",
    keywords: ["miniPIERS", "PIERS", "prééclampsie", "pronostic", "48h", "issue", "défavorable", "SpO2", "créatinine", "céphalées", "GA", "score"],
    text: "miniPIERS (von Dadelszen, Lancet 2011) :\nPrédit issue maternelle défavorable dans les 48h chez femme hospitalisée pour PE. AUC = 0.88.\n\nFORMULE :\nlogit(p) = -7.490 + (0.010 × AG_jours) + (coeff SpO2) + (1.029 × céphalées/troubles visuels) + (0.878 × douleur thoracique/dyspnée) + (coeff plaquettes) + (coeff créatinine)\n\nCOEFFICIENTS SpO2 (air ambiant) :\n≥ 96% → 0 | 93-95% → 1.08 | 90-92% → 1.52 | < 90% → 2.44\n\nCOEFFICIENTS PLAQUETTES (G/L) :\n> 150 → 0 | 100-150 → 0.58 | 50-99 → 1.26 | < 50 → 1.85\n\nCOEFFICIENTS CRÉATININE (µmol/L) :\n< 100 → 0 | 100-149 → 1.08 | ≥ 150 → 2.13\n\nINTERPRÉTATION :\n< 25% : surveillance standard. 25-50% : intensifier, discuter extraction.\n> 50% : extraction à considérer quelle que soit lAG.\n\nÉvénements cibles : éclampsie, HELLP, défaillance rénale, œdème pulmonaire, AVC, mort.",
  },
  {
    id: "cpr-doppler-fgr",
    source: "Baschat 2018 + FIGO 2021",
    domain: "OBST",
    topic: "FGR",
    title: "CPR (Cerebroplacental Ratio) — Interprétation et décision obstétricale",
    year: 2018,
    evidence: "B",
    keywords: ["CPR", "rapport", "cérébro-placentaire", "ACM", "AO", "Doppler", "FGR", "tardif", "terme", "brain", "sparing", "vasodilatation"],
    text: "CPR = IP ACM / IP Artère Ombilicale.\n\nVALEURS :\nNormal : CPR > 1.0. Pathologique : CPR < 1.0 ou < p5 (Baschat 2018).\n\nSIGNIFICATION :\nCPR < p5 → redistribution hémodynamique (brain sparing). Associé à : hypoxie fœtale subclinique, acidose, issue périnéale défavorable.\n\nFGR TARDIF (FIGO 2021) : CPR < p5 = critère auxiliaire si PFE p3-10.\n\nDÉCISION :\nCPR < 1.0 à terme (≥ 37 SA) + FGR → déclenchement, ne pas laisser post-terme.\nCNGOF : extraction 37-38 SA si CPR pathologique + FGR tardif.\nCPR 1.0-1.3 → surveillance hebdomadaire. > 1.3 → rassurant.",
  },
  {
    id: "sopk-diagnostic-traitement",
    source: "Rotterdam 2003 + ESHRE/ASRM 2023",
    domain: "GYN",
    topic: "SOPK",
    title: "SOPK — Diagnostic Rotterdam, bilan hormonal, prise en charge",
    year: 2023,
    evidence: "A",
    keywords: ["SOPK", "PCOS", "Rotterdam", "hyperandrogénie", "oligoménorrhée", "AMH", "CFA", "metformine", "létrozole", "induction", "ovulation", "HOMA"],
    text: "SOPK — CRITÈRES ROTTERDAM 2003 (2 sur 3) :\n1. Oligo-anovulation (cycles > 35 j ou < 8 cycles/an)\n2. Hyperandrogénie clinique ou biologique (testostérone élevée)\n3. Aspect polykystique : ≥ 20 follicules 2-9 mm OU volume > 10 mL\n\nMISE À JOUR ESHRE 2023 :\nAMH ≥ 3.5 ng/mL = alternative au critère morphologique. CFA ≥ 20 follicules.\n\nBILAN :\nTestostérone + SHBG + IAL, 17OHP, prolactine, TSH, LH/FSH, glycémie jeûn + insulinémie (HOMA-IR), bilan lipidique, AMH.\n\nTRAITEMENT :\nPerte pondérale si surpoids (5-10% → cycles restaurés 50%).\nPilule EP : régulation cycles + hyperandrogénie.\nInduction ovulation : Létrozole 2.5-5 mg J3-J7 (1ère ligne ESHRE 2023) | Citrate clomifène 50-150 mg (alternative) | Gonadotrophines step-up si résistance.\nMetformine si HOMA-IR élevé.\nRisques grossesse : DG (× 3), PE, prématurité.\nFIV : protocole antagoniste + trigger agoniste (prévention OHSS).",
  },
  {
    id: "rupture-uterine-hrp",
    source: "CNGOF + Expert consensus",
    domain: "OBST",
    topic: "Urgences obstétricales",
    title: "Rupture utérine et HRP — Urgences, diagnostic, prise en charge",
    year: 2022,
    evidence: "C",
    keywords: ["rupture", "utérine", "HRP", "hématome", "rétroplacentaire", "urgence", "placenta", "décollement", "CIVD", "hystérectomie", "Bandl", "choc"],
    text: "RUPTURE UTÉRINE :\nFacteurs : utérus cicatriciel +++, grande multiparité, disproportion, ocytocine excessive.\n\nSIGNES :\n- Douleur abdominale intense entre contractions ou permanente\n- Disparition des contractions (utérus silencieux)\n- Bradycardie fœtale profonde et prolongée\n- Ascension de la présentation\n- Anneau de Bandl (pré-rupture = urgence absolue)\n- Métrorragies (inconstantes, peut être endo-rupture)\n\nTRAITEMENT : laparotomie urgence absolue. Hystérorraphie si lésion nette + désir grossesse. Hystérectomie si lésions multiples ou instabilité hémodynamique.\n\nHRP (Hématome Rétro-Placentaire) :\nCLINIQUE : douleur brutale, utérus hypertonique (de bois), métrorragies noirâtres, CIVD (fibrinogène < 2 g/L), SFA ou MFIU. Occulte dans 20%.\n\nGRADES : 1 (léger) | 2 (intermédiaire, SFA) | 3 (sévère, MFIU ± CIVD).\n\nTRAITEMENT : urgence absolue. CS en urgence si fœtus vivant. Correction CIVD (PFC, fibrinogène, plaquettes).",
  },
  {
    id: "ctg-interpretation-figo2015",
    source: "FIGO 2015 + CNGOF",
    domain: "OBST",
    topic: "Monitoring fœtal",
    title: "CTG — Interprétation FIGO 2015, classification, conduite à tenir",
    year: 2015,
    evidence: "A",
    keywords: ["CTG", "cardiotocographie", "monitoring", "rythme", "cardiaque", "fœtal", "FCF", "décélération", "variabilité", "tachycardie", "bradycardie", "FIGO"],
    text: "INTERPRÉTATION CTG — FIGO 2015 :\n\nPARAMÈTRES :\n1. Fréquence de base : normale 110-160 bpm.\n2. Variabilité long terme : normale 5-25 bpm. Diminuée < 5 bpm > 40 min.\n3. Accélérations : ≥ 2 accélérations 15 bpm × 15 sec en 20 min = réactif.\n4. Décélérations :\n   DIP I (précoces) : mirroring contraction = compression tête (bénin).\n   DIP II (tardives) : décalées 30-60 sec = insuffisance placentaire (grave).\n   Variables : non uniform, < 3 min = compression cordon.\n\nCLASSIFICATION FIGO 2015 :\nNORMAL : fréq. 110-160, variabilité 5-25, ≥ 2 accélérations, pas de DIP pathologiques.\nSUSPECT : 1 élément non rassurant → enquête étiologique.\nPATHOLOGIQUE : ≥ 2 éléments non rassurants OU DIP tardives répétées OU bradycardie < 100 OU variabilité < 5 bpm > 40 min OU tracé sinusoïdal → INTERVENTION IMMÉDIATE.\n\nCONDUITE CTG PATHOLOGIQUE :\nDécubitus latéral gauche | Arrêt ocytociques | Remplissage SSI 500 mL | O2 masque 10 L/min | Tocolyse IV (Gynipral) | Extraction urgente si persistance.",
  },
  {
    id: "fiv-protocoles-eshre-2020",
    source: "ESHRE ART Guidelines 2020",
    domain: "PMA",
    topic: "FIV",
    title: "FIV — Protocoles stimulation, monitoring, trigger, ponction ovocytaire",
    year: 2020,
    evidence: "A",
    keywords: ["FIV", "stimulation", "FSH", "antagoniste", "agoniste", "monitoring", "E2", "follicule", "trigger", "hCG", "ponction", "vitrification", "freeze"],
    text: "PROTOCOLES DE STIMULATION FIV (ESHRE 2020) :\n\nANTAGONISTE GnRH (STANDARD ACTUEL) :\nFSH recombinante J2-J3. Dose selon réserve :\n  Faible réserve : 300-450 UI/j | Normale : 150-225 UI/j | Élevée/SOPK : 100-150 UI/j.\nAntagoniste (Cétrorelix 0.25 mg/j) dès follicule ≥ 14 mm ou E2 > 400 pg/mL.\nDurée : 10-12 jours.\n\nLONG AGONISTE : Désensibilisation 2 semaines (Décapeptyl). Plus de risque OHSS si trigger hCG.\n\nMONITORING : Écho TV J6, J8. E2 + LH + progestérone.\nProgestérone > 1.5 ng/mL = avancement endométrial → freeze-all.\n\nTRIGGER : ≥ 3 follicules ≥ 17 mm + E2 ≥ 300 pg/mL par follicule.\nhCG (Ovitrelle 250 µg) : trigger classique.\nAgoniste GnRH (Décapeptyl 0.2 mg) : si risque OHSS → freeze-all obligatoire.\n\nPONCTION : 36h après trigger. Écho-guidée vaginale. Aspiration follicules 16-18 mm.\nClassification ovocytes : MII (mature), MI, GV (immature).",
  },
  {
    id: "figo-myomes-palmcoein",
    source: "FIGO 2011 + CNGOF",
    domain: "GYN",
    topic: "Myomes",
    title: "Myomes utérins — Classification PALM-COEIN, impact fertilité, traitement",
    year: 2011,
    evidence: "B",
    keywords: ["myome", "fibrome", "PALM-COEIN", "FIGO", "sous-muqueux", "intramural", "sous-séreux", "saignements", "fertilité", "résection", "embolisation"],
    text: "CLASSIFICATION FIGO PALM-COEIN (2011) :\nType 0 : sous-muqueux pédiculé (100% intracavitaire).\nType 1 : sous-muqueux sessile (> 50% intracavitaire).\nType 2 : sous-muqueux (< 50% intracavitaire).\nType 3 : intramural en contact avec endomètre.\nType 4 : intramural pur.\nTypes 5-6-7 : sous-séreux.\nType 8 : autres (cervical, ligamentaire, parasitique).\n\nIMPACT FERTILITÉ :\nTypes 0-2 (sous-muqueux) : réduction taux grossesse 50% → résection hystéroscopique avant FIV.\nTypes 3-4 (intramural) : effet négatif si > 5 cm avec déformation cavitaire.\nTypes 5-7 (sous-séreux) : pas d'effet démontré.\n\nTRAITEMENT MÉDICAL :\nAgonistes GnRH : réduction 30-50% en 3 mois (préopératoire seulement).\nDIU lévonorgestrel : réduit ménorragies si myome < 3 cm.\n\nCHIRURGIE :\nMyomectomie hystéroscopique : types 0-2 (gold standard).\nCoelioscopique : types 3-6. Laparotomie : > 8 cm ou multiples.\nEmbolisation artères utérines : si pas de désir grossesse. Récidive : 30% à 5 ans.",
  },
]; // fin SEED_KB — 22 chunks